#!/usr/bin/env node
/**
 * BZZAI Helper - TUI Menu for toggling Zai API
 * No external dependencies required (gum)
 */

const fs = require('fs');
const path = require('path');
const os = require('os');

// ANSI colors for terminal
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  dim: '\x1b[2m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
  white: '\x1b[37m',
};

// Config paths
const ZAI_ROOT = process.env.ZAI_ROOT || path.join(os.homedir(), '.zai');
const ENV_FILE = path.join(ZAI_ROOT, 'env.sh');
const CLAUDE_SETTINGS = path.join(os.homedir(), '.claude', 'settings.json');

// Ensure .zai directory exists
if (!fs.existsSync(ZAI_ROOT)) {
  fs.mkdirSync(ZAI_ROOT, { recursive: true });
}

// Create example env if not exists
if (!fs.existsSync(ENV_FILE)) {
  const example = `# Zai API Configuration
# Edit this file with your API key

ZAI_AUTH_TOKEN="your-api-key-here"
ZAI_BASE_URL="https://api.z.ai/api/anthropic"
ZAI_TIMEOUT_MS="3000000"
ZAI_DEBUG="0"
`;
  fs.writeFileSync(ENV_FILE, example);
  console.log(`${colors.cyan}Created config file at:${colors.reset} ${ENV_FILE}`);
  console.log(`${colors.yellow}Please edit it with your API key:${colors.reset}`);
  console.log(`  nano ${ENV_FILE}`);
  process.exit(1);
}

// Parse env.sh file
function loadEnv() {
  const content = fs.readFileSync(ENV_FILE, 'utf8');
  const env = {};
  content.split('\n').forEach(line => {
    const match = line.match(/^(\w+)="(.*)"$/);
    if (match) {
      env[match[1]] = match[2];
    }
  });
  return env;
}

// Save env.sh file
function saveEnv(env) {
  const content = `# Zai API Configuration
# Auto-generated by bzzai-helper

ZAI_AUTH_TOKEN="${env.ZAI_AUTH_TOKEN}"
ZAI_BASE_URL="${env.ZAI_BASE_URL}"
ZAI_TIMEOUT_MS="${env.ZAI_TIMEOUT_MS}"
ZAI_DEBUG="0"
`;
  fs.writeFileSync(ENV_FILE, content);
}

// Get current status from Claude settings
function getStatus() {
  if (!fs.existsSync(CLAUDE_SETTINGS)) {
    return { enabled: false };
  }
  try {
    const content = fs.readFileSync(CLAUDE_SETTINGS, 'utf8');
    const settings = JSON.parse(content);
    const hasToken = settings.env?.ANTHROPIC_AUTH_TOKEN;
    if (hasToken) {
      return {
        enabled: true,
        url: settings.env.ANTHROPIC_BASE_URL || 'unknown',
      };
    }
  } catch (e) {
    // Ignore parse errors
  }
  return { enabled: false };
}

// Enable Zai
function enableZai(env) {
  if (!fs.existsSync(CLAUDE_SETTINGS)) {
    console.log(`${colors.red}Error: Claude settings not found at ${CLAUDE_SETTINGS}${colors.reset}`);
    return false;
  }
  const content = fs.readFileSync(CLAUDE_SETTINGS, 'utf8');
  const settings = JSON.parse(content);
  settings.env = settings.env || {};
  settings.env.ANTHROPIC_AUTH_TOKEN = env.ZAI_AUTH_TOKEN;
  settings.env.ANTHROPIC_BASE_URL = env.ZAI_BASE_URL;
  settings.env.API_TIMEOUT_MS = env.ZAI_TIMEOUT_MS;
  fs.writeFileSync(CLAUDE_SETTINGS, JSON.stringify(settings, null, 2));
  return true;
}

// Disable Zai
function disableZai() {
  if (!fs.existsSync(CLAUDE_SETTINGS)) {
    console.log(`${colors.red}Error: Claude settings not found at ${CLAUDE_SETTINGS}${colors.reset}`);
    return false;
  }
  const content = fs.readFileSync(CLAUDE_SETTINGS, 'utf8');
  const settings = JSON.parse(content);
  if (settings.env) {
    delete settings.env.ANTHROPIC_AUTH_TOKEN;
    delete settings.env.ANTHROPIC_BASE_URL;
    delete settings.env.API_TIMEOUT_MS;
  }
  fs.writeFileSync(CLAUDE_SETTINGS, JSON.stringify(settings, null, 2));
  return true;
}

// Simple TUI menu using readline
function showMenu() {
  const readline = require('readline');
  const env = loadEnv();
  const status = getStatus();

  const options = [
    { key: '1', label: 'Enable Zai', desc: 'Switch to Zai API' },
    { key: '2', label: 'Disable Zai', desc: 'Switch back to Anthropic' },
    { key: '3', label: 'Check Status', desc: 'Show current status' },
    { key: '4', label: 'Edit Config', desc: 'Edit API config' },
    { key: 'q', label: 'Quit', desc: 'Exit' },
  ];

  function render() {
    console.clear();
    console.log('');
    console.log(`${colors.magenta}${colors.bright}    ╔═════════════════════════════════╗${colors.reset}`);
    console.log(`${colors.magenta}${colors.bright}    ║     BZZAI Toggle Menu           ║${colors.reset}`);
    console.log(`${colors.magenta}${colors.bright}    ╚═════════════════════════════════╝${colors.reset}`);
    console.log('');
    console.log(`${colors.dim}    Status:${colors.reset} ${status.enabled ? `${colors.green}● Zai ENABLED${colors.reset}` : `${colors.white}○ Zai DISABLED${colors.reset}`);
    console.log('');
    console.log(`${colors.dim}    ─────────────────────────────────────${colors.reset}`);
    console.log('');

    options.forEach(opt => {
      console.log(`    ${colors.cyan}[${opt.key}]${colors.reset} ${colors.bright}${opt.label}${colors.reset} ${colors.dim}${opt.desc}${colors.reset}`);
    });
    console.log('');
    console.log(`${colors.dim}    ─────────────────────────────────────${colors.reset}`);
    console.log('');
  }

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  function ask() {
    render();
    rl.question(`${colors.cyan}Choose option:${colors.reset} `, (answer) => {
      switch (answer.trim().toLowerCase()) {
        case '1':
          rl.close();
          if (enableZai(env)) {
            console.clear();
            console.log('');
            console.log(`${colors.green}✓ Zai enabled${colors.reset}`);
            console.log('');
            console.log(`${colors.dim}Press Enter to continue...${colors.reset}`);
            const continueRl = readline.createInterface({ input: process.stdin, output: process.stdout });
            continueRl.question('', () => { continueRl.close(); showMenu(); });
          } else {
            showMenu();
          }
          break;
        case '2':
          rl.close();
          if (disableZai()) {
            console.clear();
            console.log('');
            console.log(`${colors.green}✓ Zai disabled (using Anthropic default)${colors.reset}`);
            console.log('');
            console.log(`${colors.dim}Press Enter to continue...${colors.reset}`);
            const continueRl2 = readline.createInterface({ input: process.stdin, output: process.stdout });
            continueRl2.question('', () => { continueRl2.close(); showMenu(); });
          } else {
            showMenu();
          }
          break;
        case '3':
          rl.close();
          console.clear();
          console.log('');
          const newStatus = getStatus();
          console.log(`${colors.cyan}Status:${colors.reset}`);
          if (newStatus.enabled) {
            console.log(`  ${colors.green}● Zai ENABLED${colors.reset}`);
            console.log(`  ${colors.dim}URL: ${newStatus.url}${colors.reset}`);
          } else {
            console.log(`  ${colors.white}○ Zai DISABLED (default Anthropic)${colors.reset}`);
          }
          console.log('');
          console.log(`${colors.dim}Press Enter to continue...${colors.reset}`);
          const continueRl3 = readline.createInterface({ input: process.stdin, output: process.stdout });
          continueRl3.question('', () => { continueRl3.close(); showMenu(); });
          break;
        case '4':
          rl.close();
          editConfig(env);
          break;
        case 'q':
        case 'quit':
        case 'exit':
          rl.close();
          console.clear();
          console.log('');
          console.log(`${colors.dim}Goodbye!${colors.reset}`);
          console.log('');
          process.exit(0);
          break;
        default:
          ask();
      }
    });
  }

  ask();
}

// Edit config
function editConfig(env) {
  const readline = require('readline');
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const question = (prompt) => new Promise(resolve => rl.question(prompt, resolve));

  async function doEdit() {
    console.clear();
    console.log('');
    console.log(`${colors.cyan}${colors.bright}Edit Configuration${colors.reset}`);
    console.log('');
    console.log(`${colors.dim}Current values:${colors.reset}`);
    console.log(`  Token: ${env.ZAI_AUTH_TOKEN.substring(0, 20)}...`);
    console.log(`  URL:   ${env.ZAI_BASE_URL}`);
    console.log(`  Timeout: ${env.ZAI_TIMEOUT_MS}ms`);
    console.log('');
    console.log(`${colors.dim}Press Enter to keep current value${colors.reset}`);
    console.log('');

    const newToken = await question(`${colors.cyan}Token [${colors.dim}${env.ZAI_AUTH_TOKEN.substring(0, 20)}...${colors.cyan}]:${colors.reset} `);
    const newUrl = await question(`${colors.cyan}Base URL [${colors.dim}${env.ZAI_BASE_URL}${colors.cyan}]:${colors.reset} `);
    const newTimeout = await question(`${colors.cyan}Timeout (ms) [${colors.dim}${env.ZAI_TIMEOUT_MS}${colors.cyan}]:${colors.reset} `);

    if (newToken.trim()) env.ZAI_AUTH_TOKEN = newToken.trim();
    if (newUrl.trim()) env.ZAI_BASE_URL = newUrl.trim();
    if (newTimeout.trim()) env.ZAI_TIMEOUT_MS = newTimeout.trim();

    console.log('');
    const confirm = await question(`${colors.yellow}Save changes? [y/N]:${colors.reset} `);

    rl.close();

    if (confirm.toLowerCase() === 'y') {
      saveEnv(env);
      console.log('');
      console.log(`${colors.green}✓ Config saved${colors.reset}`);
      console.log('');
      console.log(`${colors.dim}Press Enter to continue...${colors.reset}`);
      const continueRl = readline.createInterface({ input: process.stdin, output: process.stdout });
      continueRl.question('', () => { continueRl.close(); showMenu(); });
    } else {
      showMenu();
    }
  }

  doEdit();
}

// CLI mode
function cliMode(args) {
  const env = loadEnv();
  const cmd = args[0];

  switch (cmd) {
    case 'on':
      if (enableZai(env)) {
        console.log(`${colors.green}✓ Zai enabled${colors.reset}`);
      }
      break;
    case 'off':
      if (disableZai()) {
        console.log(`${colors.green}✓ Zai disabled (using Anthropic default)${colors.reset}`);
      }
      break;
    case 'status':
      const status = getStatus();
      if (status.enabled) {
        console.log(`${colors.green}● Zai ENABLED${colors.reset}`);
        console.log(`${colors.dim}URL: ${status.url}${colors.reset}`);
      } else {
        console.log(`${colors.white}○ Zai DISABLED (default Anthropic)${colors.reset}`);
      }
      break;
    default:
      console.log(`Usage: bzzai [on|off|status|menu]`);
      console.log(`  npx bzzai-helper        - Open TUI menu`);
      console.log(`  npx bzzai-helper on     - Enable Zai`);
      console.log(`  npx bzzai-helper off    - Disable Zai`);
      console.log(`  npx bzzai-helper status - Check status`);
      process.exit(1);
  }
}

// Main entry
const args = process.argv.slice(2);
if (args.length > 0 && args[0] !== 'menu') {
  cliMode(args);
} else {
  showMenu();
}
