#!/bin/bash
# Zai TUI Menu powered by Gum
# Usage: ./menu.sh or source it

ZAI_DIR="${ZAI_DIR:-$HOME/DataStore/me/claude/zai}"
ZAI_ENV_TEMPLATE="$ZAI_DIR/env.sh"
CLAUDE_SETTINGS="$HOME/.claude/settings.json"

# Load env values
if [[ -f "$ZAI_ENV_TEMPLATE" ]]; then
  source "$ZAI_ENV_TEMPLATE"
fi

# Get current status
get_status() {
  if jq -e '.env.ANTHROPIC_AUTH_TOKEN' "$CLAUDE_SETTINGS" > /dev/null 2>&1; then
    local url=$(jq -r '.env.ANTHROPIC_BASE_URL // "not set"' "$CLAUDE_SETTINGS")
    echo "🟢 Zai: ENABLED"
    echo "   Base URL: $url"
  else
    echo "⚪ Zai: DISABLED (default Anthropic)"
  fi
}

# Enable Zai
zai-on() {
  local tmp_file=$(mktemp)
  jq --arg token "$ZAI_AUTH_TOKEN" \
     --arg url "$ZAI_BASE_URL" \
     --arg timeout "$ZAI_TIMEOUT_MS" \
     '.env.ANTHROPIC_AUTH_TOKEN = $token | .env.ANTHROPIC_BASE_URL = $url | .env.API_TIMEOUT_MS = $timeout' \
     "$CLAUDE_SETTINGS" > "$tmp_file" && mv "$tmp_file" "$CLAUDE_SETTINGS"
}

# Disable Zai
zai-off() {
  local tmp_file=$(mktemp)
  jq 'del(.env.ANTHROPIC_AUTH_TOKEN) | del(.env.ANTHROPIC_BASE_URL) | del(.env.API_TIMEOUT_MS)' \
     "$CLAUDE_SETTINGS" > "$tmp_file" && mv "$tmp_file" "$CLAUDE_SETTINGS"
}

# Edit config via TUI input
edit-config() {
  # Show current values
  gum style --foreground 240 --margin "1 0" "Current values:"

  gum style --foreground 212 "  Token:    ${ZAI_AUTH_TOKEN:0:20}..."
  gum style --foreground 212 "  Base URL: $ZAI_BASE_URL"
  gum style --foreground 212 "  Timeout:  $ZAI_TIMEOUT_MS ms"
  echo ""

  # Input new values
  local new_token=$(gum input --value "$ZAI_AUTH_TOKEN" --placeholder "API Auth Token" --width 50 --header "Token")
  local new_url=$(gum input --value "$ZAI_BASE_URL" --placeholder "Base URL" --width 50 --header "Base URL")
  local new_timeout=$(gum input --value "$ZAI_TIMEOUT_MS" --placeholder "Timeout (ms)" --width 20 --header "Timeout")

  # Confirm
  echo ""
  gum confirm "Save changes?" || return 0

  # Write to env.sh
  cat > "$ZAI_ENV_TEMPLATE" <<EOF
# Zai API Configuration
# Auto-generated by zai-menu

ZAI_AUTH_TOKEN="$new_token"
ZAI_BASE_URL="$new_url"
ZAI_TIMEOUT_MS="$new_timeout"

# Debug mode (1=on, 0=off)
ZAI_DEBUG="\${ZAI_DEBUG:-0}"
EOF

  # Reload
  source "$ZAI_ENV_TEMPLATE"

  gum style --foreground 46 "✓ Config saved"
  gum spin --spinner dot --title "Waiting..." -- sleep 1
}

# Main menu
zai-menu() {
  while true; do
    # Clear screen
    clear

    # Header
    gum style \
      --foreground 212 --border-foreground 212 --border double \
      --align center --width 40 --margin "1 2" \
      "BZZAI Toggle Menu"

    # Status
    gum style --foreground 240 --margin "0 2" "$(get_status)"

    # Menu
    choice=$(gum choose \
      --cursor "▶ " \
      --header "$(gum style --foreground 240 'Select action')" \
      --margin "1 2" \
      "Enable Zai" \
      "Disable Zai" \
      "Check Status" \
      "Edit Config" \
      "Exit")

    case "$choice" in
      "Enable Zai")
        zai-on
        gum style --foreground 46 "✓ Zai enabled"
        gum spin --spinner dot --title "Waiting..." -- sleep 1
        ;;
      "Disable Zai")
        zai-off
        gum style --foreground 46 "✓ Zai disabled (default Anthropic)"
        gum spin --spinner dot --title "Waiting..." -- sleep 1
        ;;
      "Check Status")
        gum style --foreground 215 "$(get_status)"
        echo ""
        gum confirm "Continue?" || return 0
        ;;
      "Edit Config")
        edit-config
        ;;
      "Exit")
        return 0
        ;;
    esac
  done
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  zai-menu
fi
